export const BOOKS_TEMPLATE = [
  { title: "Человек в поисках смысла", author: "Виктор Франкл", category: "Психология", status: "wishlist", note: "Логотерапия, поиск смысла в страдании" },
  { title: "Бегство от свободы", author: "Эрих Фромм", category: "Психология", status: "wishlist", note: "Почему люди отказываются от свободы" },
  { title: "Архетипы и коллективное бессознательное", author: "К.Г. Юнг", category: "Психология", status: "wishlist", note: "Тень, Анима, Самость" },
  { title: "Миф о Сизифе", author: "Альбер Камю", category: "Философия", status: "wishlist", note: "Абсурд и смысл жизни" },
  { title: "Так говорил Заратустра", author: "Фридрих Ницше", category: "Философия", status: "wishlist", note: "Сверхчеловек, вечное возвращение" },
  { title: "Размышления", author: "Марк Аврелий", category: "Стоицизм", status: "wishlist", note: "Дневник римского императора" },
  { title: "Письма к Луцилию", author: "Сенека", category: "Стоицизм", status: "wishlist", note: "Практическая мудрость" },
  { title: "Думай медленно... решай быстро", author: "Даниэль Канеман", category: "Психология", status: "wishlist", note: "Система 1 и Система 2" },
  { title: "Атомные привычки", author: "Джеймс Клир", category: "Самопомощь", status: "wishlist", note: "1% улучшений каждый день" },
  { title: "Великие психологи", author: "Ирвин Ялом", category: "Психология", status: "wishlist", note: "Экзистенциальная психотерапия" },
  { title: "Дар психотерапии", author: "Ирвин Ялом", category: "Психология", status: "wishlist", note: "Письма молодому психотерапевту" },
  { title: "Великая дерзость", author: "Брене Браун", category: "Психология", status: "wishlist", note: "Уязвимость как сила" },
  { title: "Иметь или быть?", author: "Эрих Фромм", category: "Психология", status: "wishlist", note: "Два способа существования" },
  { title: "Искусство любить", author: "Эрих Фромм", category: "Психология", status: "wishlist", note: "Любовь как искусство и практика" },
  { title: "Тишина: сила интровертов", author: "Сьюзан Кейн", category: "Психология", status: "wishlist", note: "Для интровертов" },
  { title: "Воспоминания, сновидения, размышления", author: "К.Г. Юнг", category: "Психология", status: "wishlist", note: "Автобиография" },
  { title: "Семь привычек высокоэффективных людей", author: "Стивен Кови", category: "Самопомощь", status: "wishlist", note: "Классика" },
  { title: "Государство", author: "Платон", category: "Философия", status: "wishlist", note: "Идеальное общество и справедливость" },
  { title: "Никомахова этика", author: "Аристотель", category: "Философия", status: "wishlist", note: "Счастье и добродетель" },
  { title: "Страх и трепет", author: "Сёрен Кьеркегор", category: "Философия", status: "wishlist", note: "Вера, парадокс, Авраам" },
  { title: "Мир как воля и представление", author: "Артур Шопенгауэр", category: "Философия", status: "wishlist", note: "Воля к жизни и страдание" },
  { title: "Бытие и ничто", author: "Жан-Поль Сартр", category: "Философия", status: "wishlist", note: "Экзистенциализм" },
  { title: "Второй пол", author: "Симона де Бовуар", category: "Философия", status: "wishlist", note: "Феминизм и экзистенциализм" },
  { title: "Опыты", author: "Мишель Монтень", category: "Философия", status: "wishlist", note: "Эссе обо всём — гуманизм" },
  { title: "Государь", author: "Никколо Макиавелли", category: "Политика", status: "wishlist", note: "Реальная политика" },
  { title: "Искусство войны", author: "Сунь-Цзы", category: "Политика", status: "wishlist", note: "Стратегия и психология" },
  { title: "48 законов власти", author: "Роберт Грин", category: "Политика", status: "wishlist", note: "Современный Макиавелли" },
  { title: "1984", author: "Джордж Оруэлл", category: "Антиутопия", status: "wishlist", note: "Тоталитаризм, Большой Брат" },
  { title: "О дивный новый мир", author: "Олдос Хаксли", category: "Антиутопия", status: "wishlist", note: "Контроль через удовольствие" },
  { title: "451 градус по Фаренгейту", author: "Рэй Брэдбери", category: "Антиутопия", status: "wishlist", note: "Сжигание книг" },
  { title: "Мы", author: "Евгений Замятин", category: "Антиутопия", status: "wishlist", note: "Первая антиутопия XX века" },
  { title: "Рассказ служанки", author: "Маргарет Этвуд", category: "Антиутопия", status: "wishlist", note: "Теократия" },
  { title: "Заводной апельсин", author: "Энтони Бёрджесс", category: "Антиутопия", status: "wishlist", note: "Свобода воли" },
  { title: "Дорога", author: "Кормак Маккарти", category: "Антиутопия", status: "wishlist", note: "Постапокалипсис, отец и сын" },
  { title: "Преступление и наказание", author: "Ф.М. Достоевский", category: "Литература", status: "wishlist", note: "Совесть, идея, страдание" },
  { title: "Братья Карамазовы", author: "Ф.М. Достоевский", category: "Литература", status: "wishlist", note: "Бог, свобода, отцеубийство" },
  { title: "Посторонний", author: "Альбер Камю", category: "Литература", status: "wishlist", note: "Абсурд и отчуждение" },
  { title: "Чума", author: "Альбер Камю", category: "Литература", status: "wishlist", note: "Солидарность перед абсурдом" },
  { title: "Степной волк", author: "Герман Гессе", category: "Литература", status: "wishlist", note: "Двойственность личности" },
  { title: "Сиддхартха", author: "Герман Гессе", category: "Литература", status: "wishlist", note: "Путь к просветлению" },
  { title: "Процесс", author: "Франц Кафка", category: "Литература", status: "wishlist", note: "Абсурд бюрократии" },
  { title: "Сто лет одиночества", author: "Габриэль Гарсиа Маркес", category: "Литература", status: "wishlist", note: "Магический реализм" },
  { title: "Портрет Дориана Грея", author: "Оскар Уайльд", category: "Литература", status: "wishlist", note: "Красота, мораль, разложение" },
  { title: "Космос", author: "Карл Саган", category: "Наука", status: "wishlist", note: "Вселенная глазами поэта-учёного" },
  { title: "Краткая история времени", author: "Стивен Хокинг", category: "Наука", status: "wishlist", note: "От Большого взрыва до чёрных дыр" },
  { title: "Эгоистичный ген", author: "Ричард Докинз", category: "Наука", status: "wishlist", note: "Эволюция и поведение" },
  { title: "Биология добра и зла", author: "Роберт Сапольски", category: "Наука", status: "wishlist", note: "Почему мы делаем то, что делаем" },
  { title: "Вы, конечно, шутите, мистер Фейнман!", author: "Ричард Фейнман", category: "Наука", status: "wishlist", note: "Любопытство как способ жить" },
  { title: "Семь кратких уроков физики", author: "Карло Ровелли", category: "Наука", status: "wishlist", note: "Краткое и поэтичное" },
  { title: "Дао Дэ Цзин", author: "Лао-цзы", category: "Восточная философия", status: "wishlist", note: "Путь и добродетель" },
  { title: "Беседы и суждения", author: "Конфуций", category: "Восточная философия", status: "wishlist", note: "Этика отношений" },
];

export const CURIOSITY_TEMPLATE = [
  { title: "Когнитивные искажения", category: "Психология", note: "Эффект Даннинга-Крюгера, подтверждения и др." },
  { title: "Стоицизм для начинающих", category: "Философия", note: "Эпиктет, Аврелий, Сенека" },
  { title: "Привязанность по Боулби", category: "Психология", note: "Типы привязанности и отношения" },
  { title: "Основы экзистенциализма", category: "Философия", note: "Сартр, Кьеркегор, Хайдеггер" },
  { title: "Нейропластичность", category: "Наука", note: "Как мозг меняется в течение жизни" },
  { title: "Эффективные техники изучения языка", category: "Метаобучение", note: "Spaced repetition, активный recall" },
  { title: "История искусства XIX-XX веков", category: "Искусство", note: "Импрессионизм, модернизм" },
];

export const BOOK_STATUSES = [
  { value: "wishlist", label: "Хочу прочитать", emoji: "📋" },
  { value: "reading",  label: "Читаю",          emoji: "📖" },
  { value: "done",     label: "Прочитано",      emoji: "✅" },
];
